version: '3.9'
services:
  sm-mysql-server:
    image: mariadb:10.7
    environment:
      - MARIADB_ROOT_PASSWORD=masukaja
      - MARIADB_DATABASE=sm-db
    ports:
      - "33006:3306"
  stock-management:
    build: .
    depends_on:
      - sm-mysql-server
    container_name: sm-1.0
    ports:
      - "19000:8080"
    env_file:
      - "./config.env"