openapi: 3.0.0

info:
  title: My Apps
  description: this is a description
  version: 1.0.0-beta

servers:
  - url: https://test.com
    description: staging
  
tags:
  - name: User
  - name: Auth
  - name: Product
  - name: Transaction

paths:
  '/api/login':
    post:
      summary: this is a login endpoint
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: username
                password:
                  type: string
                  example: supersecretpassword
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  rescode:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: kjasldkjalksdjalkjdlaksjdkalj
        '402':
          description: user failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request, user failure
                  rescode:
                    type: number
                    example: 402
    get:
      summary: this is a get login
      tags:
        - Auth
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/success200"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          token:
                            type: string
                            example: kjasldkjalksdjalkjdlaksjdkalj

  '/api/user/{id}':
    get:
      security:
        - BearerAuth: []
      summary: this is a get profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Customer
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                  allOf:
                    - $ref: "#/components/schemas/success200"
                    - type: object
                      properties:
                        data:
                          type: object
                          properties:
                            token:
                              type: string
                              example: kjasldkjalksdjalkjdlaksjdkalj
        '402':
          $ref: "#/components/responses/402badrequest"
    update:
    delete:
  '/api/user':
    post:
      summary: this is a create user endpoint
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postUser"
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseSingleUser"

components:
  schemas:
    success200:
      type: object
      properties:
         message:
           type: string
           example: success
         rescode:
           type: number
           example: 200
  responses:
    402badrequest:
      description: user failure
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: bad request, user failure
              rescode:
                type: number
                example: 402
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
