name: "on_pull_request"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  testing:
    name: testing-api
    runs-on: ubuntu-latest
    container: golang:1.17
    services:
      mysql:
        image: mariadb:10.1
        env:
          MYSQL_ROOT_PASSWORD: masukaja
          MYSQL_DATABASE: sm-db
        ports:
          - 3306:3306
    strategy:
      matrix:
        go: [ "1.17" ]
    steps:
      - uses: actions/checkout@v2
      - name: running test
        env:
          DBHOST: mysql
          DBPASS: masukaja
          DBUSER: root
          DBPORT: 3306
          DBNAME: sm-db
        run: |
          go mod tidy
          go test ./...



